import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    breedingManagementDescription: 'Manage goat breeding records and expected kidding dates.',
    kiddingRecords: 'Kidding Records',
    newBreeding: 'New Breeding',
    newBreedingRecord: 'New Breeding Record',
    addFirstBreedingRecord: 'Add your first goat breeding record.',
    backToBreeding: 'Back to Breeding',
    language: "Language",
    english: "English",
    swahili: "Kiswahili",
    dutch: "Nederlands",

    dashboard: "Dashboard",
    goats: "Goats",
    chickens: "Chickens",
    rabbits: "Rabbits",
    inventory: "Inventory",
    finance: "Finance",
    workers: "Workers",
    reports: "Reports",
    settings: "Settings",

    rabbitFarm: "Rabbit Farm",
    feedInventory: "Feed & Inventory",
    staff: "Staff",
    system: "System",
    breeding: "Breeding",
    kidding: "Kidding",

    chickenVaccinations: "Chicken Vaccinations",
    chickenMortality: "Chicken Mortality",
    chickenMortalityDescription: "Record and manage chicken deaths",
    totalDeaths: "Total Deaths",
    rabbitBreeding: "Rabbit Breeding",
    noBreedingRecordsFound: "No breeding records found.",
    loadingBreedingRecords: "Loading breeding records...",
    expectedBirth: "Expected Birth",
    backToProfile: "Back to Profile",
    addBreeding: "Add Breeding",
    breedingHistoryFemaleRabbit: "Breeding history for this female rabbit.",
    source: "Source",
    sourcePlaceholder: "e.g. Kenchic, Farm hatchery",
    active: "Active",
    sold: "Sold",
    dead: "Dead",
    managePoultryFlock: "Manage Poultry Flock",
    deleteChickenConfirm: "Are you sure you want to delete this chicken?",
    failedDeleteChicken: "Failed to delete chicken.",
    chickenDeletedSuccessfully: "Chicken deleted successfully.",
    unknown: "Unknown",
    recordChickenVaccination: "Record Chicken Vaccination",
    failedSaveVaccination: "Failed to save vaccination.",
    chicken: "Chicken",
    selectChicken: "Select Chicken",
    recordVaccination: "Record Vaccination",
    deleteVaccinationConfirm: "Delete this vaccination record?",
    failedDeleteVaccination: "Failed to delete vaccination.",
    noVaccinationRecords: "No vaccination records found.",
    recordChickenMortality: "Record Chicken Mortality",
    failedRecordMortality: "Failed to record mortality.",
    mortalityCausePlaceholder: "Disease, Predator, Accident...",
    eggProduction: "Egg Production",
    recordSale: "Record Sale",
    totalSales: "Total Sales",
    eggsSold: "Eggs Sold",
    totalRevenue: "Total Revenue",
    pricePerEgg: "Price/Egg",
    noEggSalesFound: "No egg sales found.",
    walkInCustomer: "Walk-in Customer",
    deleteSaleConfirm: "Delete this sale?",
    dailyEggCollection: "Daily egg collection records.",
    recordProduction: "Record Production",
    deleteRecordConfirm: "Delete this record?",
    eggs: "Eggs",
    broken: "Broken",
    noEggProductionRecords: "No egg production records found.",
    eggSales: "Egg Sales",

    feedUsage: "Feed Usage",

    rabbitLitters: "Rabbit Litters",
    loadingMortalityRecords: "Loading mortality records...",
    noRabbitMortalityRecordsFound: "No rabbit mortality records found.",

    rabbitLitterDescription: "Record and track rabbit births and kits.",
    recordLitter: "Record Litter",
    action: "Action",
    loadingLitterRecords: "Loading litter records...",
    noRabbitLitterRecordsFound: "No rabbit litter records found.",

    rabbitMortality: "Rabbit Mortality",
    rabbit: "Rabbit",
    selectRabbit: "Select Rabbit",
    mortalityDate: "Mortality Date",
    cause: "Cause",
    rabbitVaccinations: "Rabbit Vaccinations",

    logout: "Logout",
    back: "Back",
    save: "Save",
    updateFeed: "Update Feed",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    close: "Close",
    search: "Search",
    searchByTagNameBreed: "Search by tag, name or breed...",
    allGoatBirths: "All goat births.",
    noKiddingRecordsFound: "No kidding records found.",
    newKidding: "Register Birth",
    searchByTagNameBreed: "Search by tag, name or breed...",
    actions: "Actions",

    name: "Name",
    date: "Date",
    status: "Status",
    notes: "Notes",
    weight: "Weight",
    color: "Color",
    breed: "Breed",
    sex: "Sex",
    healthy: "Healthy",
    sick: "Sick",
    treated: "Treated",
    saving: "Saving...",
    saveGoat: "Save Goat",
    goatStatistics: "Goat Statistics",
    currentWeight: "Current Weight",
    photoGallery: "Photo Gallery",
    noGalleryPhotos: "No gallery photos yet.",
    goatInformation: "Goat Information",
    layer: "Layer",
    broiler: "Broiler",
    cockerel: "Cockerel",
    cock: "Cock",
    hen: "Hen",
    chick: "Chick",

    manageWorkersDescription:
      "Manage users who can access Salome Young Farm.",
    role: "Role",
    created: "Created",

    changePassword: "Change Password",
    testData: "Test Data",


    kiddingDate: "Kidding Date",
    maleKids: "Male Kids",
    femaleKids: "Female Kids",
    stillborn: "Doodgeboren",
    registerKidding: "Register Kidding",

    addWeightRecord: "Add Weight Record",

    recordType: "Record Type",
    vaccination: "Vaccination",
    deworming: "Deworming",
    treatment: "Treatment",
    checkup: "Check-up",
    veterinarian: "Veterinarian",
    dosage: "Dosage",

    income: "Income",
    expense: "Expense",
    mpesa: "M-PESA",

    addRabbitBreedingRecord: "Add Rabbit Breeding Record",
    femaleRabbit: "Female Rabbit",
    maleRabbit: "Male Rabbit",
    loadingRabbit: "Loading rabbit...",
    loadingMaleRabbits: "Loading male rabbits...",

    rabbitVaccination: "Rabbit Vaccination",
    recordRabbitVaccination: "Record Rabbit Vaccination",
    vaccinationDate: "Vaccination Date",
    vaccineName: "Vaccine Name",
    nextDueDate: "Next Due Date",
    administeredBy: "Administered By",

    rabbitWeightHistory: "Rabbit Weight History",
    addRabbitWeight: "Add Rabbit Weight",
    weightDate: "Weight Date",

    item: "Item",
    quantity: "Quantity",
    price: "Price",

    female: "Female",
    male: "Male",
    tagNumber: "Tag Number",
    colour: "Colour",
    father: "Father",
    mother: "Mother",
    purchasePrice: "Purchase Price",

    generalInformation: "General Information",
    quickStatistics: "Quick Statistics",
    healthRecords: "Health Records",
    healthRecordsDescription:
      "Vaccinations, deworming and treatment history.",

    recordRabbitLitter: "Record Rabbit Litter",
    breedingRecord: "Breeding Record",
    totalKits: "Total Kits",
    liveKits: "Live Kits",
    deadKits: "Dead Kits",

    recordRabbitMortality: "Record Rabbit Mortality",
    recordDeathsDescription:
      "Record deaths and automatically update flock quantity.",


    displayPreferences: "Display Preferences",
    displayPreferencesDescription:
      "Choose your preferred language for the application.",

    profile: "Profile",
    farmInformation: "Farm Information",
    dataManagement: "Data Management",
    preferences: "Preferences",

    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    farmName: "Farm Name",

    totalAnimals: "Total Animals",
    totalAnimalRecords: "Total Animal Records",
    quickActions: "Quick Actions",
    systemStatus: "System Status",

    addGoat: "Add Goat",
    noGoatsFound: "No goats found",
    noRabbitsFound: "No rabbits found",
    farmOverview: "Farm Overview",
    feedTypes: "Feed Types",
    inventoryItems: "Inventory Items",
    addInventoryItem: "Add Inventory Item",
    addInventoryDescription: "Add feed, medicine, equipment or supplies.",
    itemName: "Item Name",
    minimumStock: "Minimum Stock",
    supplier: "Supplier",
    purchaseDate: "Purchase Date",
    purchasePriceKES: "Purchase Price (KES)",
    feed: "Feed",
    medicine: "Medicine",
    vaccine: "Vaccine",
    equipment: "Equipment",
    fuel: "Fuel",
    buildingMaterial: "Building Material",
    other: "Other",
    kg: "kg",
    bags: "bags",
    litres: "litres",
    pieces: "pieces",
    bottles: "bottles",
    packets: "packets",
    recentGoats: "Recent Goats",
    farmSummary: "Farm Summary",
    viewAll: "View All",
    tryAnotherSearch: "Try another search or add a new goat.",
    tag: "Tag",
    view: "View",
    birthDate: "Birth Date",
    addChicken: "Add Chicken",
    addRabbit: "Add Rabbit",
    addFeed: "Add Feed",
    addWorker: "Add Worker",
    financeEntry: "Finance Entry",

    goatPhoto: "Goat Photo",
    selectPhoto: "Select Photo",
    changePhoto: "Change Photo",

    basicInformation: "Basic Information",
    earTag: "Ear Tag",
    dateOfBirth: "Date of Birth",

    yes: "Yes",
    no: "No",
    loading: "Loading...",
    noRecords: "No records found.",
    success: "Success",
    error: "Error",

    welcome: "Welcome to Salome Young Farm Management System.",
    viewRecords: "View records",
    reportsDescription: "View farm reports and important information.",
    openReports: "Open Reports",
    settingsDescription: "Configure your farm management system.",
    openSettings: "Open Settings",

    update: "Update",
    cancel: "Cancel",

    financeManagement: "Finance Management",
    financeDescription:
      "Income, expenses and farm profitability.",
    financialSummary: "Financial Summary",
    financialTransactions: "Financial Transactions",
    animalSummary: "Animal Summary",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    profit: "Profit",
    transactions: "Transactions",
    addTransaction: "Add Transaction",
    dateColumn: "Date",
    recorded: "Recorded",
    type: "Type",
    category: "Category",
    description: "Description",
    amount: "Amount",
    payment: "Payment",
    noTransactions: "No transactions found.",
    financeEdit: "Edit",
    financeDelete: "Delete",

    goatManagement: "Goat Management",
    doe: "Mbuzi jike",
    selectDoe: "Chagua mbuzi jike",
    buck: "Mbuzi dume",
    selectBuck: "Chagua mbuzi dume",
    matingDate: "Tarehe ya kupandisha",
    expectedKidding: "Tarehe inayotarajiwa ya kuzaa",
    veterinarian: "Daktari wa mifugo",
    breedingManagement: "Breeding Management",
    inventoryManagement: "Inventory Management",
    feedManagement: "Feed Management",
    chickenManagement: "Chicken Management",
    rabbitManagement: "Rabbit Management",
    salomeYoungFarm: "Salome Young Farm",

    accountCreated: "Account created successfully.",
    addChickenDescription: "Add a chicken to your poultry records.",
    addFeedDescription: "Add feed to your farm records.",
    addHealthRecord: "Add Health Record",
    additionalInformation: "Additional Information",
    backToLogin: "Back to Login",
    chickenProfile: "Chicken Profile",
    createAccount: "Create Account",
    createAccountDescription: "Create a new farm account.",
    creatingAccount: "Creating account...",
    customer: "Customer",
    dailyFeedRecords: "Daily Feed Records",
    deleteFeedConfirm: "Are you sure you want to delete this feed record?",
    failedToDeleteFeed: "Failed to delete feed.",
    deleteMortalityConfirm: "Are you sure you want to delete this mortality record?",
    deleteRabbitHealthConfirm: "Are you sure you want to delete this rabbit health record?",
    deleteWorker: "Delete Worker",
    deleteWorkerConfirm: "Are you sure you want to delete this worker?",
    editChicken: "Edit Chicken",
    editWorker: "Edit Worker",
    emailAddress: "Email Address",
    emailPlaceholder: "Enter your email address",
    failedDeleteRecord: "Failed to delete record.",
    failedLoadWorkers: "Failed to load workers.",
    failedSaveChicken: "Failed to save chicken.",
    failedUpdateChicken: "Failed to update chicken.",
    farmOperations: "Farm Operations",
    financeRecords: "Finance Records",
    forgotPassword: "Forgot Password?",
    forgotPasswordDescription: "Enter your email address to reset your password.",
    hatchDate: "Hatch Date",
    loadingHealthRecords: "Loading health records...",
    manageFeedStock: "Manage Feed Stock",
    manageFinance: "Manage Finance",
    manageWorkers: "Manage Workers",
    noCategory: "No Category",
    noChickensFound: "No chickens found.",
    noFeedRecords: "No feed records found.",
    noFeedUsage: "No feed usage records found.",
    noHealthRecordsFound: "No health records found.",
    noMortalityRecords: "No mortality records found.",
    password: "Password",
    passwordTooShort: "Password is too short.",
    passwordsDoNotMatch: "Passwords do not match.",
    rabbitHealthRecords: "Rabbit Health Records",
    recordEggs: "Record Eggs",
    recordMortality: "Record Mortality",
    recordUsage: "Record Usage",
    saveChanges: "Save Changes",
    saveFeed: "Save Feed",
    saveWorker: "Save Worker",
    sendResetLink: "Send Reset Link",
    sending: "Sending...",
    serverConnectionFailed: "Server connection failed.",
    token: "Token",
    total: "Total",
    trackFarmSupplies: "Track Farm Supplies",
    unit: "Unit",
    vaccinationRecords: "Vaccination Records",
    vaccinations: "Vaccinations",
    worker: "Worker",
    noWorkersFound: "Geen werknemers gevonden.",
    workerDeleted: "Worker deleted successfully.",
    workerManagement: "Worker Management",
    recordEggSale: "Record Egg Sale",
    saleDate: "Sale Date",
    pricePerEggKES: "Price Per Egg (KES)",
    paymentMethod: "Payment Method",
    cash: "Cash",
    bank: "Bank",
    failedSaveEggSale: "Failed to save egg sale.",
    weightHistory: 'Weight History',
    trackGoatWeight: "Track the goat's weight over time.",
    backToGoat: 'Back to Goat',
    addWeight: 'Add Weight',
    weightKg: 'Weight (kg)',
    gainLoss: 'Gain/Loss',
    noWeightRecordsFound: 'No weight records found.',
    noChange: 'No change',
    breedingRecords: 'Breeding Records',
    doe: 'Doe',
    buck: 'Buck',
    matingDate: 'Mating Date',
    expectedKidding: 'Expected Kidding',
    days: 'Days',
    selectDoe: 'Select Doe',
    selectBuck: 'Select Buck',
    breedingManagementDescription: 'Expected goat breeding management records and kidding dates.',

    openWorkers: "Open Workers",
    dashboardConnected: "Dashboard connected",
    feedConnected: "Feed connected",
    inventoryConnected: "Inventory connected",
    financeConnected: "Finance connected",
    workerModuleActive: "Worker module active",
    goatModuleActive: "Goat Module Active",
    chickenModuleActive: "Chicken Module Active",
    rabbitModuleActive: "Rabbit Module Active",  },
  sw: {
    action: 'Kitendo',
    addInventoryDescription: 'Ongeza chakula, dawa, vifaa au mahitaji ya shamba.',
    addInventoryItem: 'Ongeza Bidhaa ya Hifadhi',
    bags: 'mifuko',
    birthDate: 'Tarehe ya Kuzaliwa',
    bottles: 'chupa',
    buildingMaterial: 'Vifaa vya Ujenzi',
    deadKits: 'Watoto Waliokufa',
    equipment: 'Vifaa',
    farmOverview: 'Muhtasari wa Shamba',
    farmSummary: 'Muhtasari wa Shamba',
    feedTypes: 'Aina za Chakula',
    female: 'Jike',
    fuel: 'Mafuta',
    inventoryItems: 'Bidhaa za Hifadhi',
    itemName: 'Jina la Bidhaa',
    kg: 'kg',
    litres: 'lita',
    liveKits: 'Watoto Walio Hai',
    loadingLitterRecords: 'Inapakia rekodi za vizazi...',
    loadingMortalityRecords: 'Inapakia rekodi za vifo...',
    male: 'Dume',
    medicine: 'Dawa',
    minimumStock: 'Kiwango cha Chini cha Hifadhi',
    noRabbitLitterRecordsFound: 'Hakuna rekodi za vizazi vya sungura zilizopatikana.',
    noRabbitMortalityRecordsFound: 'Hakuna rekodi za vifo vya sungura zilizopatikana.',
    noRabbitsFound: 'Hakuna sungura waliopatikana.',
    other: 'Nyingine',
    packets: 'pakiti',
    pieces: 'vipande',
    purchaseDate: 'Tarehe ya Ununuzi',
    purchasePriceKES: 'Bei ya Ununuzi (KES)',
    rabbitLitterDescription: 'Rekodi na fuatilia vizazi na watoto wa sungura.',
    recentGoats: 'Gezi wa Hivi Karibuni',
    recordLitter: 'Rekodi Kizazi',
    supplier: 'Msambazaji',
    totalKits: 'Jumla ya Watoto',
    vaccine: 'Chanjo',
    viewAll: 'Tazama Zote',
    breedingManagementDescription: 'Dhibiti rekodi za uzalishaji wa mbuzi na tarehe zinazotarajiwa za kuzaa.',
    kiddingRecords: 'Rekodi za Kuzaa',
    newBreeding: 'Uzalishaji Mpya',
    newBreedingRecord: 'Rekodi Mpya ya Uzalishaji',
    addFirstBreedingRecord: 'Ongeza rekodi yako ya kwanza ya uzalishaji wa mbuzi.',
    backToBreeding: 'Rudi kwenye uzalishaji',
    language: "Lugha",
    english: "Kiingereza",
    swahili: "Kiswahili",
    dutch: "Kiholanzi",

    dashboard: "Dashibodi",
    goats: "Mbuzi",
    chickens: "Kuku",
    rabbits: "Sungura",
    feed: "Chakula",
    inventory: "Hifadhi",
    finance: "Fedha",
    workers: "Wafanyakazi",
    reports: "Ripoti",
    settings: "Mipangilio",

    rabbitFarm: "Ufugaji wa Sungura",
    feedInventory: "Chakula na Hifadhi",
    staff: "Wafanyakazi",
    system: "Mfumo",
    breeding: "Uzalishaji",
    kidding: "Kuzalisha",

    chickenVaccinations: "Chanjo za Kuku",
    chickenMortality: "Vifo vya Kuku",
    chickenMortalityDescription: "Rekodi na dhibiti vifo vya kuku",
    totalDeaths: "Jumla ya vifo",
    rabbitBreeding: "Uzazi wa Sungura",
    noBreedingRecordsFound: "Hakuna rekodi za uzazi zilizopatikana.",
    loadingBreedingRecords: "Inapakia rekodi za uzazi...",
    expectedBirth: "Tarehe ya Kuzaliwa Inayotarajiwa",
    maleRabbit: "Sungura Dume",
    femaleRabbit: "Sungura Jike",
    backToProfile: "Rudi kwenye Wasifu",
    addBreeding: "Ongeza Uzazi",
    breedingHistoryFemaleRabbit: "Historia ya uzazi wa sungura huyu jike.",
    tagNumber: "Namba ya Tag",
    source: "Chanzo",
    sourcePlaceholder: "mfano Kenchic, Kitalu cha Shambani",
    quantity: "Idadi",
    active: "Tendaji",
    purchasePrice: "Bei ya Ununuzi",
    managePoultryFlock: "Simamia Kundi la Kuku",
    deleteChickenConfirm: "Una uhakika unataka kufuta kuku huyu?",
    failedDeleteChicken: "Imeshindikana kufuta kuku.",
    chickenDeletedSuccessfully: "Kuku amefutwa kikamilifu.",
    unknown: "Haijulikani",
    recordChickenVaccination: "Rekodi Chanjo ya Kuku",
    failedSaveVaccination: "Imeshindikana kuhifadhi chanjo.",
    chicken: "Kuku",
    selectChicken: "Chagua Kuku",
    vaccinationDate: "Tarehe ya Chanjo",
    nextDueDate: "Tarehe ya Chanjo Inayofuata",
    recordVaccination: "Rekodi Chanjo",
    deleteVaccinationConfirm: "Futa rekodi hii ya chanjo?",
    failedDeleteVaccination: "Imeshindikana kufuta chanjo.",
    noVaccinationRecords: "Hakuna rekodi za chanjo zilizopatikana.",
    recordChickenMortality: "Rekodi Vifo vya Kuku",
    failedRecordMortality: "Imeshindikana kurekodi kifo.",
    mortalityCausePlaceholder: "Ugonjwa, Mnyama, Ajali...",
    eggProduction: "Uzalishaji wa Mayai",
    recordSale: "Rekodi Mauzo",
    totalSales: "Jumla ya Mauzo",
    eggsSold: "Mayai Yaliyouzwa",
    totalRevenue: "Jumla ya Mapato",
    pricePerEgg: "Bei kwa Yai",
    noEggSalesFound: "Hakuna mauzo ya mayai yaliyopatikana.",
    walkInCustomer: "Mteja wa Moja kwa Moja",
    deleteSaleConfirm: "Una uhakika unataka kufuta mauzo haya?",
    dailyEggCollection: "Rekodi za ukusanyaji wa mayai kila siku.",
    recordProduction: "Rekodi Uzalishaji",
    deleteRecordConfirm: "Una uhakika unataka kufuta rekodi hii?",
    eggs: "Mayai",
    broken: "Yaliyovunjika",
    noEggProductionRecords: "Hakuna rekodi za uzalishaji wa mayai zilizopatikana.",
    eggSales: "Mauzo ya Mayai",

    feedUsage: "Matumizi ya Chakula",

    rabbitLitters: "Vizazi vya Sungura",
    rabbitMortality: "Vifo vya Sungura",
    rabbit: "Sungura",
    selectRabbit: "Chagua Sungura",
    mortalityDate: "Tarehe ya Kifo",
    cause: "Sababu",
    rabbitVaccinations: "Chanjo za Sungura",

    logout: "Toka",
    back: "Rudi",
    save: "Hifadhi",
    add: "Ongeza",
    edit: "Hariri",
    delete: "Futa",
    close: "Funga",
    search: "Tafuta",
    searchByTagNameBreed: "Tafuta kwa namba ya sikio, jina au aina...",
    actions: "Vitendo",

    date: "Tarehe",

    displayPreferences: "Mipangilio ya Muonekano",
    displayPreferencesDescription:
      "Chagua lugha unayopendelea kutumia kwenye programu.",

    profile: "Wasifu",
    farmInformation: "Taarifa za Shamba",
    dataManagement: "Usimamizi wa Data",
    preferences: "Mapendeleo",

    fullName: "Jina Kamili",
    email: "Barua pepe",
    phone: "Simu",
    location: "Mahali",
    farmName: "Jina la Shamba",

    totalAnimals: "Jumla ya Wanyama",
    totalAnimalRecords: "Jumla ya Rekodi za Wanyama",
    quickActions: "Vitendo vya Haraka",
    systemStatus: "Hali ya Mfumo",

    addGoat: "Ongeza Mbuzi",
    noGoatsFound: "Hakuna mbuzi waliopatikana",
    tryAnotherSearch: "Jaribu kutafuta tena au ongeza mbuzi mpya.",
    view: "Tazama",
    addChicken: "Ongeza Kuku",
    addRabbit: "Ongeza Sungura",
    addFeed: "Ongeza Chakula",
    addWorker: "Ongeza Mfanyakazi",
    financeEntry: "Ingizo la Fedha",

    changePhoto: "Badilisha Picha",

    basicInformation: "Taarifa za Msingi",
    registerNewGoat: "Sajili mbuzi mpya katika shamba.",
    goatPhoto: "Picha ya Mbuzi",
    selectPhoto: "Chagua Picha",
    imageFormats: "JPG, PNG au picha nyingine",
    tag: "Namba ya Sikio",
    name: "Jina",
    breed: "Aina",
    sex: "Jinsia",
    weight: "Uzito",
    color: "Rangi",
    status: "Hali",
    healthy: "Mwenye afya",
    sick: "Mgonjwa",
    treated: "Ametibiwa",
    sold: "Imeuzwa",
    dead: "Amekufa",
    notes: "Maelezo",
    saving: "Inahifadhi...",
    saveGoat: "Hifadhi Mbuzi",
    cancel: "Ghairi",
    earTag: "Namba ya Sikio",
    dateOfBirth: "Tarehe ya Kuzaliwa",

    yes: "Ndiyo",
    no: "Hapana",
    loading: "Inapakia...",
    noRecords: "Hakuna rekodi zilizopatikana.",
    success: "Imefanikiwa",
    error: "Hitilafu",

    welcome:
      "Karibu kwenye Mfumo wa Usimamizi wa Salome Young Farm.",
    viewRecords: "Tazama rekodi",
    reportsDescription:
      "Tazama ripoti za shamba na taarifa muhimu.",
    openReports: "Fungua Ripoti",
    settingsDescription:
      "Sanidi mfumo wako wa usimamizi wa shamba.",
    openSettings: "Fungua Mipangilio",

    financeManagement: "Usimamizi wa Fedha",
    financeDescription:
      "Mapato, matumizi na faida ya shamba.",
    totalIncome: "Jumla ya Mapato",
    totalExpenses: "Jumla ya Matumizi",
    profit: "Faida",
    transactions: "Miamala",
    addTransaction: "Ongeza Muamala",
    dateColumn: "Tarehe",
    recorded: "Imerekodiwa",
    type: "Aina",
    category: "Kategoria",
    description: "Maelezo",
    amount: "Kiasi",
    payment: "Malipo",
    noTransactions: "Hakuna miamala iliyopatikana.",
    financeEdit: "Hariri",
    financeDelete: "Futa",

    goatManagement: "Usimamizi wa Mbuzi",
    allGoatBirths: "Alle geitengeboorten.",
    noKiddingRecordsFound: "Geen geboorteregistraties gevonden.",
    newKidding: "Geboorte registreren",
    doe: "Geit",
    selectDoe: "Selecteer geit",
    buck: "Bok",
    selectBuck: "Selecteer bok",
    matingDate: "Dekdatum",
    expectedKidding: "Verwachte geboorte",
    veterinarian: "Dierenarts",
    breedingManagement: "Usimamizi wa Uzazi",
    inventoryManagement: "Usimamizi wa Hifadhi",
    feedManagement: "Usimamizi wa Chakula",
    chickenManagement: "Usimamizi wa Kuku",
    rabbitManagement: "Usimamizi wa Sungura",
    salomeYoungFarm: "Salome Young Farm",

    accountCreated: "Akaunti imeundwa kwa mafanikio.",
    addChickenDescription: "Ongeza kuku kwenye rekodi za kuku.",
    addFeedDescription: "Ongeza chakula kwenye rekodi za shamba.",
    addHealthRecord: "Ongeza Rekodi ya Afya",
    additionalInformation: "Taarifa Zaidi",
    backToLogin: "Rudi kwenye Kuingia",
    chickenProfile: "Wasifu wa Kuku",
    createAccount: "Unda Akaunti",
    createAccountDescription: "Unda akaunti mpya ya shamba.",
    creatingAccount: "Inaunda akaunti...",
    customer: "Mteja",
    dailyFeedRecords: "Rekodi za Kila Siku za Chakula",
    deleteFeedConfirm: "Una uhakika unataka kufuta rekodi hii ya chakula?",
    deleteMortalityConfirm: "Una uhakika unataka kufuta rekodi hii ya kifo?",
    deleteRabbitHealthConfirm: "Una uhakika unataka kufuta rekodi hii ya afya ya sungura?",
    deleteWorker: "Futa Mfanyakazi",
    deleteWorkerConfirm: "Una uhakika unataka kumfuta mfanyakazi huyu?",
    editChicken: "Hariri Kuku",
    editWorker: "Hariri Mfanyakazi",
    emailAddress: "Anwani ya Barua Pepe",
    emailPlaceholder: "Weka anwani yako ya barua pepe",
    failedDeleteRecord: "Imeshindikana kufuta rekodi.",
    failedLoadWorkers: "Imeshindikana kupakia wafanyakazi.",
    failedSaveChicken: "Imeshindikana kuhifadhi kuku.",
    failedUpdateChicken: "Imeshindikana kusasisha kuku.",
    farmOperations: "Shughuli za Shamba",
    financeRecords: "Rekodi za Fedha",
    forgotPassword: "Umesahau Nenosiri?",
    forgotPasswordDescription: "Weka anwani yako ya barua pepe ili kuweka upya nenosiri lako.",
    hatchDate: "Tarehe ya Kutotolewa",
    loadingHealthRecords: "Inapakia rekodi za afya...",
    manageFeedStock: "Simamia Hifadhi ya Chakula",
    manageFinance: "Simamia Fedha",
    manageWorkers: "Simamia Wafanyakazi",
    noCategory: "Hakuna Kategoria",
    noChickensFound: "Hakuna kuku waliopatikana.",
    noFeedRecords: "Hakuna rekodi za chakula zilizopatikana.",
    noFeedUsage: "Hakuna rekodi za matumizi ya chakula zilizopatikana.",
    noHealthRecordsFound: "Hakuna rekodi za afya zilizopatikana.",
    noMortalityRecords: "Hakuna rekodi za vifo zilizopatikana.",
    password: "Nenosiri",
    passwordTooShort: "Nenosiri ni fupi sana.",
    passwordsDoNotMatch: "Nenosiri hazilingani.",
    rabbitHealthRecords: "Rekodi za Afya ya Sungura",
    recordEggs: "Rekodi Mayai",
    recordMortality: "Rekodi Kifo",
    recordUsage: "Rekodi Matumizi",
    saveChanges: "Hifadhi Mabadiliko",
    saveFeed: "Hifadhi Chakula",
    saveWorker: "Hifadhi Mfanyakazi",
    sendResetLink: "Tuma Kiungo cha Kuweka Upya",
    sending: "Inatuma...",
    serverConnectionFailed: "Muunganisho wa seva umeshindikana.",
    token: "Tokeni",
    total: "Jumla",
    trackFarmSupplies: "Fuatilia Vifaa vya Shamba",
    unit: "Kipimo",
    vaccinationRecords: "Rekodi za Chanjo",
    vaccinations: "Chanjo",
    worker: "Mfanyakazi",
    noWorkersFound: "Geen werknemers gevonden.",
    workerDeleted: "Mfanyakazi amefutwa kwa mafanikio.",
    workerManagement: "Usimamizi wa Wafanyakazi",
    action: "Kitendo",
    addInventoryDescription: "Ongeza chakula, dawa, vifaa au mahitaji ya shamba.",
    addInventoryItem: "Ongeza Kitu cha Hifadhi",
    bags: "mifuko",
    birthDate: "Tarehe ya Kuzaliwa",
    bottles: "chupa",
    buildingMaterial: "Nyenzo za Ujenzi",
    deadKits: "Jumla ya Watoto Waliokufa",
    equipment: "Vifaa",
    farmOverview: "Muhtasari wa Shamba",
    farmSummary: "Muhtasari wa Shamba",
    feedTypes: "Aina za Chakula",
    female: "Jike",
    fuel: "Mafuta",
    inventoryItems: "Vitu vya Hifadhi",
    itemName: "Jina la Kitu",
    kg: "kg",
    litres: "lita",
    liveKits: "Watoto Walio Hai",
    loadingLitterRecords: "Inapakia rekodi za vizazi...",
    loadingMortalityRecords: "Inapakia rekodi za vifo...",
    male: "Dume",
    medicine: "Dawa",
    minimumStock: "Kiwango cha Chini cha Hifadhi",
    noRabbitLitterRecordsFound: "Hakuna rekodi za vizazi vya sungura zilizopatikana.",
    noRabbitMortalityRecordsFound: "Hakuna rekodi za vifo vya sungura zilizopatikana.",
    noRabbitsFound: "Hakuna sungura waliopatikana.",
    other: "Nyingine",
    packets: "pakiti",
    pieces: "vipande",
    purchaseDate: "Tarehe ya Ununuzi",
    purchasePriceKES: "Bei ya Ununuzi (KES)",
    rabbitLitterDescription: "Sajili na fuatilia vizazi na watoto wa sungura.",
    recentGoats: "Mbuzi wa Hivi Karibuni",
    recordLitter: "Rekodi Kizazi",
    supplier: "Msambazaji",
    totalKits: "Jumla ya Watoto",
    vaccine: "Chanjo",
    viewAll: "Tazama Zote",
    recordEggSale: "Rekodi Uuzaji wa Mayai",
    saleDate: "Tarehe ya Uuzaji",
    pricePerEggKES: "Bei kwa Yai (KES)",
    paymentMethod: "Njia ya Malipo",
    cash: "Fedha Taslimu",
    bank: "Benki",
    failedSaveEggSale: "Imeshindikana kuhifadhi uuzaji wa mayai.",
    weightHistory: 'Historia ya Uzito',
    trackGoatWeight: 'Fuatilia uzito wa mbuzi kwa muda.',
    backToGoat: 'Rudi kwa Mbuzi',
    addWeight: 'Ongeza Uzito',
    weightKg: 'Uzito (kg)',
    gainLoss: 'Ongezeko/Upungufu',
    noWeightRecordsFound: 'Hakuna rekodi za uzito zilizopatikana.',
    noChange: 'Hakuna mabadiliko',
    breedingRecords: 'Rekodi za Uzazi',
    doe: 'Mbuzi Jike',
    buck: 'Mbuzi Dume',
    matingDate: 'Tarehe ya Kupandisha',
    expectedKidding: 'Tarehe Inayotarajiwa ya Kuzaa',
    days: 'Siku',
    selectDoe: 'Chagua mbuzi jike',
    selectBuck: 'Chagua mbuzi dume',
    veterinarian: 'Daktari wa mifugo',
    breedingManagementDescription: 'Beheer fokregistraties van geiten en verwachte geboortedata.',


    openWorkers: "Fungua Wafanyakazi",
    dashboardConnected: "Dashibodi imeunganishwa",
    feedConnected: "Chakula kimeunganishwa",
    inventoryConnected: "Hifadhi imeunganishwa",
    financeConnected: "Fedha imeunganishwa",
    workerModuleActive: "Moduli ya wafanyakazi inafanya kazi",
    goatModuleActive: "Moduli ya mbuzi inafanya kazi",
    chickenModuleActive: "Moduli ya kuku inafanya kazi",
    rabbitModuleActive: "Moduli ya sungura inafanya kazi",  },
    registerKidding: "Sajili Kuzaliwa",
    allGoatBirths: "Kuzaliwa kwa mbuzi wote.",
    noKiddingRecordsFound: "Hakuna rekodi za kuzaliwa kwa mbuzi zilizopatikana.",
    newKidding: "Sajili Kuzaliwa kwa Mbuzi",


  nl: {
    accountCreated: 'Account succesvol aangemaakt.',
    action: 'Actie',
    addChickenDescription: 'Voeg een kip toe aan uw pluimveeregistratie.',
    addFeedDescription: 'Voeg voer toe aan uw bedrijfsregistratie.',
    addHealthRecord: 'Gezondheidsregistratie toevoegen',
    addInventoryDescription: 'Voeg voer, medicijnen, apparatuur of benodigdheden toe.',
    addInventoryItem: 'Voorraaditem toevoegen',
    additionalInformation: 'Aanvullende informatie',
    backToLogin: 'Terug naar inloggen',
    bags: 'zakken',
    birthDate: 'Geboortedatum',
    bottles: 'flessen',
    buildingMaterial: 'Bouwmateriaal',
    chickenProfile: 'Kippenprofiel',
    createAccount: 'Account aanmaken',
    createAccountDescription: 'Maak een account aan voor het Salome Young Farm Managementsysteem.',
    creatingAccount: 'Account wordt aangemaakt...',
    customer: 'Klant',
    dailyFeedRecords: 'Dagelijkse voeregistraties',
    deadKits: 'Dode jongen',
    deleteFeedConfirm: 'Weet u zeker dat u deze voerregistratie wilt verwijderen?',
    deleteMortalityConfirm: 'Weet u zeker dat u deze sterfteregistratie wilt verwijderen?',
    deleteRabbitHealthConfirm: 'Weet u zeker dat u deze gezondheidsregistratie van het konijn wilt verwijderen?',
    deleteWorker: 'Werknemer verwijderen',
    deleteWorkerConfirm: 'Weet u zeker dat u deze werknemer wilt verwijderen?',
    editChicken: 'Kip bewerken',
    editWorker: 'Werknemer bewerken',
    emailAddress: 'E-mailadres',
    emailPlaceholder: 'Voer uw e-mailadres in',
    equipment: 'Apparatuur',
    failedDeleteRecord: 'Registratie verwijderen mislukt.',
    failedLoadWorkers: 'Werknemers laden mislukt.',
    failedSaveChicken: 'Kip opslaan mislukt.',
    failedUpdateChicken: 'Kip bijwerken mislukt.',
    farmOperations: 'Bedrijfsactiviteiten',
    farmOverview: 'Bedrijfsoverzicht',
    farmSummary: 'Bedrijfssamenvatting',
    feedTypes: 'Voersoorten',
    female: 'Vrouwelijk',
    financeRecords: 'Financiële registraties',
    forgotPassword: 'Wachtwoord vergeten?',
    forgotPasswordDescription: 'Voer uw e-mailadres in om uw wachtwoord opnieuw in te stellen.',
    fuel: 'Brandstof',
    hatchDate: 'Uitkomstdatum',
    inventoryItems: 'Voorraadartikelen',
    itemName: 'Naam van item',
    kg: 'kg',
    litres: 'liter',
    liveKits: 'Levende jongen',
    loadingHealthRecords: 'Gezondheidsregistraties laden...',
    loadingLitterRecords: 'Worprecords laden...',
    loadingMortalityRecords: 'Sterfteregistraties laden...',
    male: 'Mannelijk',
    manageFeedStock: 'Voervoorraad beheren',
    manageFinance: 'Financiën beheren',
    manageWorkers: 'Werknemers beheren',
    medicine: 'Medicijnen',
    minimumStock: 'Minimale voorraad',
    noCategory: 'Geen categorie',
    noChickensFound: 'Geen kippen gevonden.',
    noFeedRecords: 'Geen voerregistraties gevonden.',
    noFeedUsage: 'Geen voergebruiksregistraties gevonden.',
    noHealthRecordsFound: 'Geen gezondheidsregistraties gevonden.',
    noMortalityRecords: 'Geen sterfteregistraties gevonden.',
    noRabbitLitterRecordsFound: 'Geen worprecords van konijnen gevonden.',
    noRabbitMortalityRecordsFound: 'Geen sterfteregistraties van konijnen gevonden.',
    noRabbitsFound: 'Geen konijnen gevonden.',
    noWorkersFound: 'Geen werknemers gevonden.',
    other: 'Overig',
    packets: 'pakjes',
    password: 'Wachtwoord',
    passwordTooShort: 'Wachtwoord is te kort.',
    passwordsDoNotMatch: 'Wachtwoorden komen niet overeen.',
    pieces: 'stuks',
    purchaseDate: 'Aankoopdatum',
    purchasePriceKES: 'Aankoopprijs (KES)',
    rabbitHealthRecords: 'Gezondheidsregistraties van konijnen',
    rabbitLitterDescription: 'Registreer en volg geboorten en jongen van konijnen.',
    recentGoats: 'Recente geiten',
    recordEggs: 'Eieren registreren',
    recordLitter: 'Worp registreren',
    recordMortality: 'Sterfte registreren',
    recordUsage: 'Gebruik registreren',
    saveChanges: 'Wijzigingen opslaan',
    saveFeed: 'Voer opslaan',
    saveWorker: 'Werknemer opslaan',
    sendResetLink: 'Resetlink verzenden',
    sending: 'Verzenden...',
    serverConnectionFailed: 'Verbinding met de server mislukt.',
    supplier: 'Leverancier',
    token: 'Token',
    total: 'Totaal',
    totalKits: 'Totaal aantal jongen',
    trackFarmSupplies: 'Bedrijfsbenodigdheden bijhouden',
    unit: 'Eenheid',
    vaccinationRecords: 'Vaccinatieregistraties',
    vaccinations: 'Vaccinaties',
    vaccine: 'Vaccin',
    viewAll: 'Alles bekijken',
    worker: 'Werknemer',
    noWorkersFound: "Geen werknemers gevonden.",
    workerDeleted: 'Werknemer succesvol verwijderd.',
    workerManagement: 'Werknemersbeheer',
    breedingManagementDescription: 'Beheer fokregistraties van geiten en verwachte geboortedata.',
    kiddingRecords: 'Geboorteregistraties',
    newBreeding: 'Nieuwe fokregistratie',
    newBreedingRecord: 'Nieuwe fokregistratie',
    addFirstBreedingRecord: 'Voeg uw eerste fokregistratie van een geit toe.',
    backToBreeding: 'Terug naar fokkerij',
    language: "Taal",
    english: "Engels",
    swahili: "Swahili",
    dutch: "Nederlands",

    dashboard: "Dashboard",
    goats: "Geiten",
    chickens: "Kippen",
    rabbits: "Konijnen",
    feed: "Voer",
    inventory: "Voorraad",
    finance: "Financiën",
    workers: "Werknemers",
    reports: "Rapporten",
    settings: "Instellingen",

    rabbitFarm: "Konijnenhouderij",
    feedInventory: "Voer & Voorraad",
    staff: "Personeel",
    system: "Systeem",
    breeding: "Fokkerij",
    kidding: "Geboorten",

    chickenVaccinations: "Kippenvaccinaties",
    chickenMortality: "Kippensterfte",
    chickenMortalityDescription: "Kippensterfte registreren en beheren",
    totalDeaths: "Totaal aantal sterfgevallen",
    rabbitBreeding: "Konijnenfokkerij",
    noBreedingRecordsFound: "Geen fokregistraties gevonden.",
    loadingBreedingRecords: "Fokregistraties laden...",
    expectedBirth: "Verwachte Geboorte",
    maleRabbit: "Mannelijk Konijn",
    femaleRabbit: "Vrouwelijk Konijn",
    backToProfile: "Terug naar Profiel",
    addBreeding: "Fokregistratie Toevoegen",
    breedingHistoryFemaleRabbit: "Fokgeschiedenis van dit vrouwelijke konijn.",
    tagNumber: "Tagnummer",
    source: "Bron",
    sourcePlaceholder: "bijv. Kenchic, boerderijkwekerij",
    quantity: "Aantal",
    active: "Actief",
    purchasePrice: "Aankoopprijs",
    managePoultryFlock: "Kippenbestand beheren",
    deleteChickenConfirm: "Weet u zeker dat u deze kip wilt verwijderen?",
    failedDeleteChicken: "Kip verwijderen mislukt.",
    chickenDeletedSuccessfully: "Kip succesvol verwijderd.",
    unknown: "Onbekend",
    recordChickenVaccination: "Kippenvaccinatie registreren",
    vaccineName: "Naam van vaccin",
    dosage: "Dosering",
    administeredBy: "Toegediend door",
    failedSaveVaccination: "Vaccinatie opslaan mislukt.",

    failedSaveVaccination: "Vaccinatie opslaan mislukt.",
    chicken: "Kip",
    selectChicken: "Kip selecteren",
    vaccinationDate: "Vaccinatiedatum",
    nextDueDate: "Volgende Vervaldatum",
    recordVaccination: "Vaccinatie Registreren",
    deleteVaccinationConfirm: "Deze vaccinatieregistratie verwijderen?",
    failedDeleteVaccination: "Vaccinatie verwijderen mislukt.",
    noVaccinationRecords: "Geen vaccinatieregistraties gevonden.",
    recordChickenMortality: "Kippensterfte Registreren",
    failedRecordMortality: "Registreren van sterfte mislukt.",
    mortalityCausePlaceholder: "Ziekte, Roofdier, Ongeval...",
    eggProduction: "Eierproductie",
    recordSale: "Verkoop Registreren",
    totalSales: "Totale Verkopen",
    eggsSold: "Verkochte Eieren",
    totalRevenue: "Totale Omzet",
    pricePerEgg: "Prijs per Ei",
    manageUsersDescription: "Beheer gebruikers die toegang hebben tot Salome Young Farm.",
    role: "Rol",
    created: "Aangemaakt",
    noEggSalesFound: "Geen eierverkopen gevonden.",
    walkInCustomer: "Inloopklant",
    deleteSaleConfirm: "Weet u zeker dat u deze verkoop wilt verwijderen?",
    dailyEggCollection: "Dagelijkse registraties van eierverzameling.",
    recordProduction: "Productie Registreren",
    deleteRecordConfirm: "Weet u zeker dat u deze registratie wilt verwijderen?",
    eggs: "Eieren",
    broken: "Gebroken",
    noEggProductionRecords: "Geen registraties van eierproductie gevonden.",
    eggSales: "Eierverkoop",

    feedUsage: "Voergebruik",

    rabbitLitters: "Konijnenworpen",
    rabbitMortality: "Konijnensterfte",
    rabbit: "Konijn",
    selectRabbit: "Selecteer Konijn",
    mortalityDate: "Sterftedatum",
    cause: "Oorzaak",
    rabbitVaccinations: "Konijnenvaccinaties",

    logout: "Uitloggen",
    back: "Terug",
    save: "Opslaan",
    add: "Toevoegen",
    edit: "Bewerken",
    delete: "Verwijderen",
    close: "Sluiten",
    search: "Zoeken",
    searchByTagNameBreed: "Zoeken op oormerk, naam of ras...",
    actions: "Acties",

    date: "Datum",

    displayPreferences: "Weergavevoorkeuren",
    displayPreferencesDescription:
      "Kies de taal die u voor de applicatie wilt gebruiken.",

    profile: "Profiel",
    farmInformation: "Bedrijfsinformatie",
    dataManagement: "Gegevensbeheer",
    preferences: "Voorkeuren",

    fullName: "Volledige naam",
    email: "E-mail",
    phone: "Telefoon",
    location: "Locatie",
    farmName: "Naam van de boerderij",

    totalAnimals: "Totaal aantal dieren",
    totalAnimalRecords: "Totaal aantal dierregistraties",
    quickActions: "Snelle acties",
    systemStatus: "Systeemstatus",

    addGoat: "Geit toevoegen",
    noGoatsFound: "Geen geiten gevonden",
    tryAnotherSearch: "Probeer een andere zoekopdracht of voeg een nieuwe geit toe.",
    view: "Bekijken",
    addChicken: "Kip toevoegen",
    addRabbit: "Konijn toevoegen",
    addFeed: "Voer toevoegen",
    addWorker: "Werknemer toevoegen",
    financeEntry: "Financiële invoer",

    changePhoto: "Foto wijzigen",

    basicInformation: "Basisinformatie",
    registerNewGoat: "Registreer een nieuwe geit op de boerderij.",
    goatPhoto: "Geitenfoto",
    selectPhoto: "Foto selecteren",
    imageFormats: "JPG, PNG of andere afbeeldingen",
    tag: "Tag",
    name: "Naam",
    breed: "Ras",
    sex: "Geslacht",
    weight: "Gewicht",
    color: "Kleur",
    status: "Status",
    healthy: "Gezond",
    sick: "Ziek",
    treated: "Behandeld",
    sold: "Verkocht",
    dead: "Dood",
    notes: "Notities",
    saving: "Opslaan...",
    saveGoat: "Geit opslaan",
    cancel: "Annuleren",
    earTag: "Oormerk",
    dateOfBirth: "Geboortedatum",

    yes: "Ja",
    no: "Nee",
    loading: "Laden...",
    noRecords: "Geen gegevens gevonden.",
    success: "Gelukt",
    error: "Fout",

    welcome:
      "Welkom bij het Salome Young Farm Managementsysteem.",
    viewRecords: "Records bekijken",
    reportsDescription:
      "Bekijk bedrijfsrapporten en belangrijke informatie.",
    openReports: "Rapporten openen",
    settingsDescription:
      "Configureer uw bedrijfsbeheersysteem.",
    openSettings: "Instellingen openen",

    financeManagement: "Financieel Beheer",
    financeDescription:
      "Inkomsten, uitgaven en winstgevendheid van de boerderij.",
    totalIncome: "Totale inkomsten",
    totalExpenses: "Totale uitgaven",
    profit: "Winst",
    transactions: "Transacties",
    addTransaction: "Transactie toevoegen",
    dateColumn: "Datum",
    recorded: "Geregistreerd",
    type: "Type",
    category: "Categorie",
    description: "Beschrijving",
    amount: "Bedrag",
    payment: "Betaling",
    noTransactions: "Geen transacties gevonden.",
    financeEdit: "Bewerken",
    financeDelete: "Verwijderen",
    goatManagement: "Geitenbeheer",
    doe: "Doe",
    selectDoe: "Select Doe",
    buck: "Buck",
    selectBuck: "Select Buck",
    matingDate: "Mating Date",
    expectedKidding: "Expected Kidding",
    veterinarian: "Veterinarian",
    breedingManagement: "Fokkerijbeheer",
    inventoryManagement: "Voorraadbeheer",
    feedManagement: "Voerbeheer",
    chickenManagement: "Kippenbeheer",
    rabbitManagement: "Konijnenbeheer",
    salomeYoungFarm: "Salome Young Farm",

    accountCreated: "Account succesvol aangemaakt.",
    action: "Actie",
    addChickenDescription: "Voeg een kip toe aan uw pluimveeregistratie.",
    addFeedDescription: "Voeg voer toe aan uw boerderijregistratie.",
    addHealthRecord: "Gezondheidsregistratie toevoegen",
    addInventoryDescription: "Voeg voer, medicijnen, apparatuur of benodigdheden toe.",
    addInventoryItem: "Voorraaditem toevoegen",
    additionalInformation: "Aanvullende informatie",
    backToLogin: "Terug naar inloggen",
    bags: "zakken",
    birthDate: "Geboortedatum",
    bottles: "flessen",
    buildingMaterial: "Bouwmateriaal",
    chickenProfile: "Kippenprofiel",
    createAccount: "Account aanmaken",
    createAccountDescription: "Maak een nieuw account aan.",
    creatingAccount: "Account wordt aangemaakt...",
    customer: "Klant",
    dailyFeedRecords: "Dagelijkse voerregistraties",
    deadKits: "Dode jongen",
    deleteFeedConfirm: "Weet u zeker dat u deze voerregistratie wilt verwijderen?",
    deleteMortalityConfirm: "Weet u zeker dat u deze sterfteregistratie wilt verwijderen?",
    deleteRabbitHealthConfirm: "Weet u zeker dat u deze gezondheidsregistratie van het konijn wilt verwijderen?",
    deleteWorker: "Werknemer verwijderen",
    deleteWorkerConfirm: "Weet u zeker dat u deze werknemer wilt verwijderen?",
    editChicken: "Kip bewerken",
    editWorker: "Werknemer bewerken",
    emailAddress: "E-mailadres",
    emailPlaceholder: "Voer uw e-mailadres in",
    equipment: "Apparatuur",
    failedDeleteRecord: "Registratie verwijderen mislukt.",
    failedLoadWorkers: "Werknemers laden mislukt.",
    failedSaveChicken: "Kip opslaan mislukt.",
    failedUpdateChicken: "Kip bijwerken mislukt.",
    farmOperations: "Boerderijactiviteiten",
    farmOverview: "Boerderijoverzicht",
    farmSummary: "Boerderijoverzicht",
    feedTypes: "Voersoorten",
    female: "Vrouwelijk",
    financeRecords: "Financiële registraties",
    forgotPassword: "Wachtwoord vergeten?",
    forgotPasswordDescription: "Voer uw e-mailadres in om uw wachtwoord opnieuw in te stellen.",
    fuel: "Brandstof",
    hatchDate: "Uitkomstdatum",
    inventoryItems: "Voorraadartikelen",
    itemName: "Naam van item",
    kg: "kg",
    litres: "liter",
    liveKits: "Levende jongen",
    loadingHealthRecords: "Gezondheidsregistraties laden...",
    loadingLitterRecords: "Worprecords laden...",
    loadingMortalityRecords: "Sterfteregistraties laden...",
    male: "Mannelijk",
    manageFeedStock: "Voervoorraad beheren",
    manageFinance: "Financiën beheren",
    manageWorkers: "Werknemers beheren",
    medicine: "Medicijnen",
    minimumStock: "Minimumvoorraad",
    noCategory: "Geen categorie",
    noChickensFound: "Geen kippen gevonden.",
    noFeedRecords: "Geen voerregistraties gevonden.",
    noFeedUsage: "Geen voergebruiksregistraties gevonden.",
    noHealthRecordsFound: "Geen gezondheidsregistraties gevonden.",
    noMortalityRecords: "Geen sterfteregistraties gevonden.",
    noRabbitLitterRecordsFound: "Geen konijnenworprecords gevonden.",
    noRabbitMortalityRecordsFound: "Geen konijnensterfteregistraties gevonden.",
    noRabbitsFound: "Geen konijnen gevonden.",
    other: "Overig",
    packets: "pakjes",
    password: "Wachtwoord",
    passwordTooShort: "Wachtwoord is te kort.",
    passwordsDoNotMatch: "Wachtwoorden komen niet overeen.",
    pieces: "stuks",
    purchaseDate: "Aankoopdatum",
    purchasePriceKES: "Aankoopprijs (KES)",
    rabbitHealthRecords: "Gezondheidsregistraties van konijnen",
    rabbitLitterDescription: "Registreer en volg geboorten en jongen van konijnen.",
    recentGoats: "Recente geiten",
    recordEggs: "Eieren registreren",
    recordLitter: "Worp registreren",
    recordMortality: "Sterfte registreren",
    recordUsage: "Gebruik registreren",
    saveChanges: "Wijzigingen opslaan",
    saveFeed: "Voer opslaan",
    saveWorker: "Werknemer opslaan",
    sendResetLink: "Resetlink verzenden",
    sending: "Verzenden...",
    serverConnectionFailed: "Verbinding met de server mislukt.",
    supplier: "Leverancier",
    token: "Token",
    total: "Totaal",
    totalKits: "Totaal aantal jongen",
    trackFarmSupplies: "Boerderijbenodigdheden bijhouden",
    unit: "Eenheid",
    vaccinationRecords: "Vaccinatieregistraties",
    vaccinations: "Vaccinaties",
    vaccine: "Vaccin",
    viewAll: "Alles bekijken",
    worker: "Werknemer",
    noWorkersFound: "Geen werknemers gevonden.",
    workerDeleted: "Werknemer succesvol verwijderd.",
    workerManagement: "Werknemersbeheer",
    recordEggSale: "Eierverkoop registreren",
    saleDate: "Verkoopdatum",
    pricePerEggKES: "Prijs per ei (KES)",
    paymentMethod: "Betaalmethode",
    cash: "Contant",
    bank: "Bank",
    failedSaveEggSale: "Eierverkoop opslaan mislukt.",
    weightHistory: 'Gewichtsgeschiedenis',
    trackGoatWeight: 'Volg het gewicht van de geit in de loop van de tijd.',
    backToGoat: 'Terug naar geit',
    addWeight: 'Gewicht toevoegen',
    weightKg: 'Gewicht (kg)',
    gainLoss: 'Toename/Afname',
    noWeightRecordsFound: 'Geen gewichtsregistraties gevonden.',
    noChange: 'Geen verandering',
    breedingRecords: 'Fokregistraties',
    doe: 'Geit',
    buck: 'Bok',
    matingDate: 'Dekdatum',
    expectedKidding: 'Verwachte geboortedatum',
    days: 'Dagen',
    selectDoe: 'Selecteer geit',
    selectBuck: 'Selecteer bok',
    veterinarian: 'Dierenarts',
    breedingManagementDescription: 'Beheer fokregistraties van geiten en verwachte geboortedata.',
    allGoatBirths: "Alle geitengeboorten.",
    noKiddingRecordsFound: "Geen geboorteregistraties gevonden.",
    newKidding: "Geboorte registreren",

    openWorkers: "Werknemers openen",
    dashboardConnected: "Dashboard verbonden",
    feedConnected: "Voer verbonden",
    inventoryConnected: "Voorraad verbonden",
    financeConnected: "Financiën verbonden",
    workerModuleActive: "Werknemersmodule actief",
    goatModuleActive: "Geitenmodule actief",
    chickenModuleActive: "Kippenmodule actief",
    registerKidding: "Geboorte registreren",

    rabbitModuleActive: "Konijnenmodule actief",  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("syf_language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("syf_language", language);
  }, [language]);

  function t(key) {
    return (
      translations[language]?.[key] ??
      translations.en?.[key] ??
      key
    );
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export default LanguageContext;
